name: Cleanup Expired Tokens

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点执行
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 清理过期令牌
      run: python scripts/token_cleaner.py

    - name: 提交清理结果
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || (git commit -m "Cleanup: Remove expired tokens" && git push)
